name: ci
on:
  push:
  pull_request:
jobs:
  runner-job:
    runs-on: ubuntu-latest
    name: setup go
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.20'
    - run: go get -t -v ./...
    - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
    - uses: codecov/codecov-action@v3
      name: Upload coverage reports to Codecov
      
